# Generated by Django 4.0.4 on 2022-04-19 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='Автор комментария')),
                ('content', models.TextField(verbose_name='Текст комментария')),
                ('id_kor', models.PositiveIntegerField(default=0, verbose_name='ID референта')),
                ('level', models.PositiveIntegerField(blank=True, default=0, verbose_name='Уровень вложенности')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания комментария')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='blog.posts', verbose_name='Статья')),
            ],
            options={
                'ordering': ('time_create',),
            },
        ),
    ]
