# Generated by Django 4.0.4 on 2022-05-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='artilce',
            new_name='article',
        ),
    ]
