# Generated by Django 4.0.4 on 2022-05-20 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_artilce_comments_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='blog.articles', verbose_name='Статья'),
        ),
    ]
