# Generated by Django 4.0.4 on 2022-04-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='referent',
            field=models.CharField(blank=True, max_length=255, verbose_name='Референт'),
        ),
    ]
