# Generated by Django 4.0.4 on 2022-04-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_referent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='id_kor',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID референта'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='referent',
            field=models.CharField(blank=True, max_length=255, verbose_name='Референт'),
        ),
    ]
