# Generated by Django 4.0.4 on 2022-04-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comment_author_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id_kor',
            field=models.IntegerField(default=0, verbose_name='ID референта'),
        ),
    ]
