# Generated by Django 4.0.4 on 2022-04-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comment_id_kor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='referent',
        ),
        migrations.AddField(
            model_name='comment',
            name='level',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=255, verbose_name='Уровень вложенности'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id_kor',
            field=models.PositiveIntegerField(default=0, verbose_name='ID референта'),
        ),
    ]
