# Generated by Django 4.0.4 on 2022-04-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_comment_referent_comment_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='level',
            field=models.PositiveIntegerField(blank=True, verbose_name='Уровень вложенности'),
        ),
    ]
