# Generated by Django 4.0.4 on 2022-04-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_comment_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='level',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Уровень вложенности'),
        ),
    ]
